### ISSUE TITLE
missing characters

### ISSUE THREAD

**Issue by 1250364116** [therealdreg/okhi#1]
hi. i used your program and understood that in fast speed typing two problem occurs. first some characters missed and second 
sometimes uart1 give synchronization error.

**Comment by therealdreg** [comment]
Can you test this temp firmware? send me feedback, (still beta, but better) 

[20241231084058.zip](https://github.com/user-attachments/files/18280038/20241231084058.zip)

Thx @1250364116

**Comment by 1250364116** [comment]
Thanks. The problem was not for code. It was a parsing problem not related
to this code.

در تاریخ سه‌شنبه ۳۱ دسامبر ۲۰۲۴،‏ ۱۱:۱۳ Dreg ***@***.***>
نوشت:
